name: move-to-another

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex    # "ubuntu" is a more generic container
                               # using "pandoc/latex" because of dependencies
                               # used in the specific "build.sh"
    steps:
      - uses: actions/checkout@v4
      # - name: creates output
      #   run:  sh ./build.sh # some command from your repository that creates
                            # output to "source-directory" ("output" in the example)
      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main # docs https://cpina.github.io/push-to-another-repository-docs/configuration.html#source-directory https://cpina.github.io/push-to-another-repository-docs/generic-example.html#generic-example
        env:
          SSH_DEPLOY_KEY: ${{ secrets.SSH_DEPLOY_KEY }}
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'images'
          destination-github-username: 'redlfox'
          destination-repository-name: 'resource-search-download-archive'
          user-name: 'github-actions[bot]'
          user-email: github-actions[bot]@users.noreply.github.com
          target-branch: main
